id = "lit"
name = "lit"
description = "Lit support."
version = "0.1.0"
schema_version = 1
authors = ["Florian Sanders <sanders.florian@gmail.com>"]
repository = "https://github.com/florian-sanders/zed-lit"

[grammars.javascript]
repository = "https://github.com/tree-sitter/tree-sitter-javascript"
commit = "a92640f158c208ca3be28b560b838b2bd60e8eac"

